import "./globals.css";
import { SmoothScrolling } from "@/app/_components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/images/apple.svg" sizes="any" />
        <title>Apple Iphone</title>
      </head>
      <body>
        <SmoothScrolling>{children}</SmoothScrolling>
        {/* {children} */}
      </body>
    </html>
  );
}
